#pragma once

#include <AG_HAL/AG_HAL_Boards.h>
#include <AG_CANManager/AG_CANSensor.h>

#ifndef HAL_EFI_ENABLED
#define HAL_EFI_ENABLED !HAL_MINIMIZE_FEATURES && BOARD_FLASH_SIZE > 1024
#endif

#ifndef AG_EFI_BACKEND_DEFAULT_ENABLED
#define AG_EFI_BACKEND_DEFAULT_ENABLED HAL_EFI_ENABLED
#endif

#ifndef AG_EFI_CURRAWONG_ECU_ENABLED
#define AG_EFI_CURRAWONG_ECU_ENABLED AG_EFI_BACKEND_DEFAULT_ENABLED && HAL_MAX_CAN_PROTOCOL_DRIVERS
#endif

#ifndef AG_EFI_DRONECAN_ENABLED
#define AG_EFI_DRONECAN_ENABLED AG_EFI_BACKEND_DEFAULT_ENABLED && HAL_MAX_CAN_PROTOCOL_DRIVERS && HAL_CANMANAGER_ENABLED
#endif

#ifndef AG_EFI_NWPWU_ENABLED
#define AG_EFI_NWPWU_ENABLED AG_EFI_BACKEND_DEFAULT_ENABLED && HAL_MAX_CAN_PROTOCOL_DRIVERS
#endif

#ifndef AG_EFI_SCRIPTING_ENABLED
#define AG_EFI_SCRIPTING_ENABLED (AG_EFI_BACKEND_DEFAULT_ENABLED && AP_SCRIPTING_ENABLED)
#endif

#ifndef AG_EFI_SERIAL_MS_ENABLED
#define AG_EFI_SERIAL_MS_ENABLED AG_EFI_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_EFI_SERIAL_LUTAN_ENABLED
#define AG_EFI_SERIAL_LUTAN_ENABLED AG_EFI_BACKEND_DEFAULT_ENABLED
#endif
