#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AG_AttitudeControl',
            'AG_InputManager',
            'AG_PrecLand',
            'AG_Sprayer',
            'AG_Autorotation',
            'AG_WPNav',
            'AG_Camera',
            'AG_IRLock',
            'AG_InertialNav',
            'AG_Motors',
            'AG_RCMapper',
            'AGP_Avoidance',
            'AG_AdvancedFailsafe',
            'AG_SmartRTL',
            'AG_Beacon',
            'AG_Arming',
            'AG_WheelEncoder',
            'AG_Winch',
            'AG_Follow',
            'AG_LTM_Telem',
            'AG_Devo_Telem',
            'AG_OSD',
            'AG_AutoTune',
            'AG_KDECAN',
        ],
    )

    bld.ap_program(
        program_name='arducopter',
        program_groups=['bin', 'copter'],
        use=vehicle + '_libs',
        defines=['FRAME_CONFIG=MULTICOPTER_FRAME'],
        )
