#pragma once

#include <AG_HAL/AG_HAL_Boards.h>

#include <AG_EFI/AG_EFI_config.h>
#include <AG_Generator/AG_Generator.h>

#ifndef AG_RPM_ENABLED
#define AG_RPM_ENABLED 1
#endif

#ifndef AG_RPM_BACKEND_DEFAULT_ENABLED
#define AG_RPM_BACKEND_DEFAULT_ENABLED AG_RPM_ENABLED
#endif

#ifndef AG_RPM_EFI_ENABLED
#define AG_RPM_EFI_ENABLED AG_RPM_BACKEND_DEFAULT_ENABLED && HAL_EFI_ENABLED
#endif

#ifndef AG_RPM_ESC_TELEM_ENABLED
#define AG_RPM_ESC_TELEM_ENABLED AG_RPM_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_RPM_HARMONICNOTCH_ENABLED
#define AG_RPM_HARMONICNOTCH_ENABLED AG_RPM_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_RPM_PIN_ENABLED
#define AG_RPM_PIN_ENABLED AG_RPM_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_RPM_SIM_ENABLED
#define AG_RPM_SIM_ENABLED AG_RPM_BACKEND_DEFAULT_ENABLED && AP_SIM_ENABLED
#endif

#ifndef AG_RPM_GENERATOR_ENABLED
#define AG_RPM_GENERATOR_ENABLED AG_RPM_BACKEND_DEFAULT_ENABLED && HAL_GENERATOR_ENABLED
#endif
