#!/usr/bin/env python
# encoding: utf-8

import fnmatch
import sys

try:
    import em
except ImportError:
    print("you need to install empy with 'python -m pip install empy==3.3.4'")
    sys.exit(1)

try:
    import pexpect
except ImportError:
    print("you need to install pexpect with 'python -m pip install pexpect'")
    sys.exit(1)
    

def build(bld):
    targets = bld.ap_periph_boards()
    valid_target = False
    for t in targets:
        if fnmatch.fnmatch(bld.env.BOARD, t):
            valid_target = True
    if not valid_target:
        return

    if bld.env.AP_PERIPH_HEAVY:
        libraries = bld.ap_get_all_libraries()
        libraries.extend(['AG_ADSB/sagetech-sdk'])
        bld.env.DEFINES += ['HAL_BOARD_AP_PERIPH_HEAVY']
    else:
        libraries = ['AG_Common',
                     'AG_HAL',
                     'AG_HAL_Empty',
                     'AG_Math',
                     'AG_BoardConfig',
                     'AG_BattMonitor',
                     'AG_CANManager',
                     'AG_Param',
                     'StorageManager',
                     'AG_FlashStorage',
                     'AG_RAMTRON',
                     'AG_GPS',
                     'AG_SerialManager',
                     'AG_RTC',
                     'AG_Compass',
                     'AG_NMEA_Output',
                     'AG_Baro',
                     'Filter',
                     'AG_InternalError',
                     'AG_Airspeed',
                     'AG_RangeFinder',
                     'AG_ROMFS',
                     'AG_TemperatureSensor',
                     'AG_MSP',
                     'SRV_Channel',
                     'AG_Notify',
                     'AG_SerialLED',
                     'AG_Filesystem',
                     'AG_InertialSensor',
                     'AG_AccelCal',
                     'AG_Logger',
                     'AG_PID',
                     'AG_ESC_Telem',
                     'AG_Stats',
                     'AG_EFI',
                     'AG_CheckFirmware',
                     'AG_Proximity',
                     ]
    bld.ap_stlib(
        name= 'AP_Periph_libs',
        dynamic_source='modules/DroneCAN/libcanard/dsdlc_generated/src/**.c',
        ap_vehicle='AP_Periph',
        ap_libraries= libraries,
        use='dronecan',
        exclude_src=[
            'libraries/AG_HAL_ChibiOS/Storage.cpp'
        ]
    )

    # build external libcanard library
    bld.stlib(source='../../modules/DroneCAN/libcanard/canard.c',
              name='libcanard',
              use='dronecan',
              target='libcanard')

    bld.ap_program(
        program_name='AP_Periph',
        use=['AP_Periph_libs', 'libcanard', 'dronecan'],
        program_groups=['bin','AP_Periph'],
    )
