#pragma once

#include <AG_HAL/AG_HAL_Boards.h>

#ifndef AG_GPS_BACKEND_DEFAULT_ENABLED
#define AG_GPS_BACKEND_DEFAULT_ENABLED 1
#endif

#ifndef AG_GPS_ERB_ENABLED
  #define AG_GPS_ERB_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_GSOF_ENABLED
  #define AG_GPS_GSOF_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_NMEA_ENABLED
  #define AG_GPS_NMEA_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_NMEA_UNICORE_ENABLED
  #define AG_GPS_NMEA_UNICORE_ENABLED AG_GPS_NMEA_ENABLED
#endif

#ifndef AG_GPS_NOVA_ENABLED
  #define AG_GPS_NOVA_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_SBF_ENABLED
  #define AG_GPS_SBF_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_SBP_ENABLED
  #define AG_GPS_SBP_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_SBP2_ENABLED
   #define AG_GPS_SBP2_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_SIRF_ENABLED
  #define AG_GPS_SIRF_ENABLED AG_GPS_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AG_GPS_UBLOX_ENABLED
  #define AG_GPS_UBLOX_ENABLED 1
#endif
